### ISSUE TITLE
small UI improvements

### ISSUE THREAD

**Issue by MichaelKreil** [robbi5/pulse#1]
Its hard to get an overview over 420 domains / 93 agencies. So my 2 suggestions:
1. set default "number of entries per page" from 10 to e.g. 50
2. more compact layout for "Nach Behörde", e.g. wider title column and lower height of table rows

**Comment by robbi5** [comment]
Thanks for the suggestions :)
the default number of items per page is now 25, 50 looked a bit too large.
margin and layout of the progress bars is now smaller.

Hope that looks a little bit better now, if you have more suggestions feel free to reopen.

**Comment by MichaelKreil** [comment]
Like, and by the way: Thanks for the great work! :)
